### ISSUE TITLE
Add animation support

### ISSUE THREAD

**Issue by ZhongmouLi** [JoshuaLampert/clean-math-presentation#1]
Hi Joshua Lampert,

Thanks for your template <clean-math> and it is so nice for presentation in Engineering.

I would like to ask if you can add support to allow animation in touring? For instance, pause and meanwhile?

Thanks advance.

**Comment by JoshuaLampert** [comment]
Hi @ZhongmouLi, I am glad you like it. As the template uses touying, you should already be able to use `pause` and `meanwhile` from touying. You can checkout the [documentation of touying](https://touying-typ.github.io/docs/dynamic/simple) to see how you can use it. If you have any problems with that, feel free to post a minimal example.

**Comment by ZhongmouLi** [comment]
@JoshuaLampert , Thanks for your reply.

I tired `pause` in the template using online typist.app, however it does not work as expected.

For instance, when I add a pause in a Focus slide and a Theorem slide, it does not generate additional slides for animation.

<img width="1132" alt="Screenshot 2024-12-15 at 19 37 52" src="https://github.com/user-attachments/assets/9d371282-2f71-4fa9-832e-d0cbbe8f5638" />

**Comment by JoshuaLampert** [comment]
Hi @ZhongmouLi. I cannot reproduce this. Here is a link to a project including the `#pause` you inserted in the screenshot above and it works for me as expected: https://typst.app/project/rnhfaOQjwdvswTHjPttOYh. Are you sure you didn't include the `handout: true` option in the template (which excludes all animations from the pdf)? If the issue persists, it would be really helpful if you could provide a link to a project so I can see the complete source. Thanks!

**Comment by ZhongmouLi** [comment]
@JoshuaLampert , thanks for your reply. It is my issue as I included #import "@preview/polylux:0.3.1": * after yours. That is the issue.  After removing it, it works as expected.

Thanks again for your efforts.

**Comment by JoshuaLampert** [comment]
Glad to hear it works.
